### ISSUE TITLE
error!

### ISSUE THREAD

**Issue by liamxg** [jmcastagnetto/my_map_prompt_monday#1]
Dear @jmcastagnetto,

When I run the code `dengue-in-peru-2023-epiweek-13.R`, it has error:
Zoom: 6
Fetching 15 missing tiles
  |===================================================================================| 100%
...complete!
Error in `ggspatial::annotation_map_tile()`:
! Problem while converting geom to grob.
ℹ Error occurred in the 1st layer.
Caused by error in `check.dimensions()`:
! Zero tiles were loaded for type stamenwatercolor
Run `rlang::last_trace()` to see where the error occurred.

**Comment by jmcastagnetto** [comment]
Sorry, I cannot reproduce this error in Ubuntu Linux 22.04 or 24.04, with R 4.4 or 4.3. Looks to me like a possible issue with corrupted tiles or something particular with ggspatial. I'd suggest checking the repo for that package: https://github.com/paleolimbot/ggspatial

**Comment by liamxg** [comment]
thanks. Do you know any other methods instead of ggspatial?
