### ISSUE TITLE
 a figure with `NA`

### ISSUE THREAD

**Issue by liamxg** [jmcastagnetto/my_map_prompt_monday#2]
Dear @jmcastagnetto,

I like your plot, and I use the same code as yours for `2023-05-01_urban-rural`, but I find that the figure has a `NA`:

<img width="508" alt="image" src="https://github.com/jmcastagnetto/my_map_prompt_monday/assets/46078579/b8a547e0-1c29-46d0-a316-7ece03a5e4fb">

**Comment by jmcastagnetto** [comment]
Usually I make sure that the department names have been properly mapped and transliterated to ASCII (e.g. "Á" => "A"). But, the one you are getting there as NA corresponds to "Áncash" -- check that the name has been mapped appropriately in the rural and urban population datasets, as well as in the map data obtained using GADM.

HTH

**Comment by jmcastagnetto** [comment]
Usually I make sure that the department names have been properly mapped and transliterated to ASCII (e.g. "Á" => "A"). But, the one you are getting there as NA corresponds to "Áncash" -- check that the name has been mapped appropriately in the rural and urban population datasets, as well as in the map data obtained using GADM. Take into account that labels in GADM might change from one version to the next.

HTH
